### ISSUE TITLE
Searching tools crashes repl

### ISSUE THREAD

**Issue by DillonB07** [lafkpages/Nodeval#3]
Searching for a specific tool in the new tab menu crashes the repl session.

**Comment by lafkpages** [comment]
This is because when searching for tools, Replit also searches for files. And to search for files, it uses RipGrep. If it crashed, it was probably because you didn't have RipGrep installed. You can install it on MacOS via [homebrew](https://formulae.brew.sh/formula/ripgrep):

```sh
brew install ripgrep
```

And for Windows idk just search it up.

I've also made Nodeval show you a warning if you don't have RipGrep installed.
